name: action-repository-dispatch
description: https://github.com/champ-oss/action-repository-dispatch

inputs:
  GITHUB_TOKEN:
    description: 'github token used to run action'
    required: true
  EVENT:
    description: 'event call'
    required: true
  ORG_NAME:
    description: 'org name'
    required: true
  REPO_NAME:
    description: 'repo name'
    required: true
  VERSION:
    description: 'client payload data'
    required: true
  GITHUB_REF:
    description: 'git ref'
    required: true
  GITHUB_SHA:
    description: 'git sha'
    required: false
runs:
  using: "composite"
  steps:
    - name: run python script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        EVENT: ${{ inputs.EVENT }}
        ORG_NAME: ${{ inputs.ORG_NAME }}
        REPO_NAME: ${{ inputs.REPO_NAME }}
        VERSION: ${{ inputs.VERSION }}
        GITHUB_REF: ${{ inputs.GITHUB_REF }}
        GITHUB_SHA: ${{ inputs.GITHUB_SHA }}
      run: |
        python ${GITHUB_ACTION_PATH}/action-repository-dispatch.py