name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repository dispatch
        uses: champ-oss/action-repository-dispatch@main
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          REPO_NAME: "action-repository-dispatch"
          ORG_NAME: "champ-oss"
          EVENT: "build-event"
          GITHUB_SHA: "${{ github.sha }}"
          GITHUB_REF: "${{ github.ref }}"