name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: env
      - name: repository dispatch
        uses: atxplangl/action-repository-dispatch-caller@main
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          REPO_NAME: "action-repository-dispatch"
          ORG_NAME: "champ-oss"
          EVENT: "build-event"
          VERSION: "1.0.0"
          GITHUB_SHA: "${{ github.sha }}"
          GITHUB_REF: "${{ github.ref }}"